
def complement(x):
    if x=="A":
        return "T"
    elif x == "C":
        return "G"
    elif x == "G":
        return "C"
    elif x== "T":
        return "A"
    
s = "GATATCGACAATCCGGATCTTTAAGCCTTCGCCGTGTGGCTCTACTCGTAGCGCAAGTAGCCGCTATTCCATAGCTGTCGATGCATGGCGGCCGGGAGAGTACAGATGAATGAGCGATTGCACTGTGACCATACGCGCATAACGACCTGAACCTGAATGTGCTGAGATGGTTGCCGTCGTGGTCTCGTACTACCCGAGGCCATGCTTCCGGGACTTGCTCCACAACTGTGGGATTGCTATAATAAAACCGCGTGGATTCAGTTAGTCCGTGGAGGTGTGTACGTAGGGTGTGTCCTTAAGTTTATCACGACAGGTCACCTCTATTCCTATTTCTTTTTGAGACTGCGTTGAAGTAGAAGATGCCTCCAAATCACATACTCCATTCCGGGCTTCGGGACTAAAGGCGTTTTCGCGCAGGAAACGTCACGTAAGGTTTGAATGGTAGATCGATTCCACGGAGCTTATGACCAGCTGGGGTCAAAATTTAGTTAGTTCCTGATCGTAATTATTCGTGCCACCAAGCAAACACTACATTTGTGATTCGCAAAAGGATGTAACGAGATCGCCCCATCAGCTACTATAACCCCCGGGAGGCTCCAAACTTAACAGTCAGCACGGGGATGAGCGGCCTGTCTCATCATAAGCCGAGAGATTTACTTTATGATCTATCGGAAATCTATGATCTACACAATCGAGTGACGGACCATTTGAAGTGCAGGCTCTGGTTCACATTCCCGGCGCCGAATAGTAAGAGAGGCAGAGTTGTATATACACGCGCCGGTCCTAACAACAAGACCACAGATGGTGAACTAACACGCCCGCATTTCTAGGCCCGTTGGTTTAAACGCAATACCACAGCCAGACCCGGATG"
reversed_s = s[::-1]

reverse_complement = ''.join(complement(base) for base in reversed_s)

print(reverse_complement)


# print(complement("A"))

#for base in DNA

